### PR TITLE
Fixes the checks for Patreon module

### LINKED ISSUE #492: S3 Setting won't work with Patreon Module
Sequencer db will not be imported because a few checks expect the module to be locally present.

### PR DESCRIPTION
**Pull request by DarkByteZero**
Fixes #492

### CODE REVIEW

**Comment by otigon** [comment]
This won't be added unfortunately. The upcoming release in ~1 week restructures most of this, and I've configured the internal A-A database to be versioned. For that to work you'll need a JB2A manifest active in your game world so A-A can check your JB2A version and build the database accordingly. 
 It's not strictly required, but unless you do that you'll have to manually configure newer JB2A animations using the Custom field vs built in select menus. 

I'll take a look to see if anything here can be used with the next version

**Comment by otigon** [comment]
I'd recommend getting with JB2A on their discord as they have a way to have their module active in the base Foundry game while still hosting the files on an S3 server

**Comment by DarkByteZero** [comment]
so native support for s3 will be removed from this module ?

**Comment by otigon** [comment]
S3 will still be supported, I'm speaking to how A-A will handle checking the version of the JB2A you have. If you don't have the main JB2A file in your world you will miss out on the A-A database versioning for future releases

**Comment by DarkByteZero** [comment]
But i would need to have the module locally installed? That would defeat the purpose of using s3.

**Comment by otigon** [comment]
That's why I recommend getting with JB2A, see comment above. They can tell you how to have their manifest active in the game while still hosting externally

**Comment by DarkByteZero** [comment]
But the manifest is also on the s3, wouldn't it be possible to read it from there to get the version?

**Comment by otigon** [comment]
No that is not possible I'm any way I know of. I'll just say this once again, you can have your JB2A animation files on an S3 server AND have the rest of the files installed/loaded in your Foundry game. This has many benefits because it will also register the JB2A database with Sequencer. You can get with the JB2A folks on their discord if you don't know how to do that

**Pull request closed without merging**
