### PR TITLE
Safety checks for pf1 message flags

### PR DESCRIPTION
**Pull request by dmrickey**
Added safety checks for messages that don't originate from the pf1 system (i.e. macros/mods).

### CODE REVIEW

**Comment by otigon** [comment]
I'll mege this in, And then I have to roll back your previous PR because you broke multiple things in other systems. After this I'm not doing anything else with those module

**Comment by dmrickey** [comment]
> I'll mege this in, And then I have to roll back your previous PR because you broke multiple things in other systems. After this I'm not doing anything else with those module

The previous PR that added more for functionality or the one for the pf1 hook?

**Comment by otigon** [comment]
It's probably #681

**Comment by otigon** [comment]
actually that shouldn't have affected anything outside of PF1, so not sure what broke 5e

**Pull request merged**
