### PR TITLE
Update deprecation warnings in dbMerge.js

### PR DESCRIPTION
**Pull request by gambit07**
Update global isNewerVersion to foundry.utils.isNewerVersion to fix deprecation warnings

### CODE REVIEW

**Comment by otigon** [comment]
Is this deprecated starting in V12?

**Comment by lucasmiranda2711** [comment]
Confirming, the warning started at version 12.
image

**Comment by otigon** [comment]
So in this instance, I'm still maintaining support for V11 with Sequencer, so this would have to check the version and use the new one if on V12, but still use the old one for users on V11

**Comment by gambit07** [comment]
> So in this instance, I'm still maintaining support for V11 with Sequencer, so this would have to check the version and use the new one if on V12, but still use the old one for users on V11

Actually after looking, foundry.utils was already present in V11, there was just no deprecation warning when using it globally. In V12, the deprecation warning was added for global usage. So these two pr's should be fine for both V11 and V12. I'm planning to continue working through them and will send pr's here as I do

**Pull request merged**
