### PR TITLE
Tormenta 20 handler

### PR DESCRIPTION
**Pull request by YuriAlessandro**
Tormenta 20 is an brazilian system very similar to DnD and very popular around here.

I added support to it, and also portuguese language translations.

### CODE REVIEW

**Comment by otigon** [comment]
Hey, this is excellent. I'll get it merged in today after work and push a release. Thanks!

**Comment by YuriAlessandro** [comment]
Wow, nice to hear that. 

I'm having a little problem, when I click on some option on tab "Animate" it returns me to first tab.

I don't know very well yet if this is a problem on the system code or some miscode my here.

Did you face this problem already before?

**Comment by otigon** [comment]
That is handled on line 207 of item-sheet-config.js . It's just a matter of looking at the where the tab is located to reactivate it on a Render. I can download the system and take a look as well later today.

There are event listeners that set this.activate = true to tell it to reactivate the tab on a render

**Comment by YuriAlessandro** [comment]
Thanks, with this tip I was able to fix. As a said, Tormenta is pretty based on DnD and the FVTT module is also based on the D&D module.

I also fixed the spells animations, because the token size info was different (I just added an workaround in the handler to not change others functions).

**Pull request merged**
